### ISSUE TITLE
win11 报错

### ISSUE THREAD

**Issue by Sev73n** [hunmer/VideoManager#1]
![image](https://user-images.githubusercontent.com/16495885/166422470-5f7fbb6a-8696-4b0e-adc3-9fa692c45e2a.png)

是java环境不对吗 其他的java软件都ok

**Comment by hunmer** [comment]
把软件整个目录移到除c:\Programe Files\外的位置，win11后这个目录被特别保护了没读写权限

**Comment by Sev73n** [comment]
> 

是不是win11软件默认得安装目录应该改一下了耶

**Comment by hunmer** [comment]
> > 
> 
> 是不是win11软件默认得安装目录应该改一下了耶

已修复
